<?
die('here');
$content .= "<strong>";
if($resCli['pessoa'] == 'F'){    if(!empty($resCli['nome']))        $content .= "" . strtoupper($resCli['nome']). ",";
    if(!empty($resCli['nacionalidade']))        $content .= "" . $resCli['nacionalidade']. ", " ;
    if(!empty($resCli['estado_civil']))        $content .= "" . RetornaEstadoCivil($resCli['estado_civil']). ", " ;
    if(!empty($resCli['profissao']))        $content .= "" . $resCli['profissao']. ", " ;
    if(!empty($resCli['rg']))        $content .= "portador da cédula de identidade, RG nº " .$resCli['rg']. ", ";
    if(!empty($resCli['cpf']))        $content .= "inscrito no CPF nº " .$resCli['cpf']. " ";
}if($resCli['pessoa'] == 'J'){    if(!empty($resCli['razao']))        $content .= "<strong>" .strtoupper($resCli['razao']). ", </strong>";
    if(!empty($resCli['cnpj']))        $content .= "inscrita no CNPJ/MF sob o nº " .$resCli['cnpj']. ", ";
    if(!empty($resCli['inscricao']))        $content .= "inscrição estadual o nº " .$resCli['inscricao']. " ";
}if(!empty($resCli['logradouro'])){    if($resCli['pessoa'] == 'J'){        $content .= "com sede na " .$resCli['logradouro']. ", ";
    }else{        $content .= "residente e domiciliado na " .$resCli['logradouro']. ", ";
    }}if(!empty($resCli['numero']))    $content .= "" . $resCli['numero']. ", ";
if(!empty($resCli['complemento']))    $content .= "" . $resCli['complemento']. ", ";
if(!empty($resCli['bairro']))    $content .= "" . $resCli['bairro']. ", ";
if(!empty($resCli['cep']))    $content .= "CEP: " .$resCli['cep']. " ";
if(!empty($resCli['cidade']))    $content .= "" . $resCli['cidade']. " - " .strtoupper($resCli['estado']). " ";
if(!empty($resCli['responsavel'])){    $content .= "neste ato representada por " . $resCli['responsavel']. ", ";
    if(!empty($resCli['civil']))        $content .= "" . $resCli['civil']. ", ";
    if(!empty($resCli['cpfContato']))        $content .= "inscrito no CPF nº " .$resCli['cpfContato']. ", ";
    if(!empty($resCli['rgContato']))        $content .= "portador da cédula de identidade, RG nº " .$resCli['rgContato']. ", ";
    if(!empty($resCli['logradouroContato']))        $content .= "residente e domiciliado na " .$resCli['logradouroContato']. ", ";
    if(!empty($resCli['numeroContato']))        $content .= "" . $resCli['numeroContato']. ", ";
    if(!empty($resCli['complementoContato']))        $content .= "" . $resCli['complementoContato']. ", ";
    if(!empty($resCli['bairroContato']))        $content .= "" . $resCli['bairroContato']. ", ";
    if(!empty($resCli['cepContato']))        $content .= "CEP: " .$resCli['cepContato']. " ";
    if(!empty($resCli['cidadeContato']))        $content .= "" . $resCli['cidadeContato']. " - " .strtoupper($resCli['estadoContato']). " ";
    if(!empty($resCli['email_responsavel']))        $content .= "" . $resCli['email_responsavel']. ", ";
}if(!empty($resCon['id_pessoa_secundario'])){    //$content .= "e <b>" .strtoupper($resCliSec['nome']). ", </b>" .$resCliSec['nacionalidade']. ", " .$resCliSec['civil']. ", " .$resCliSec['profissao']. ", portador da cédula de identidade, RG nº " .$resCliSec['rg']. ", inscrito no CPF nº " .$resCliSec['cpf']. ", residente e domiciliado na " .$resCliSec['logradouro']. ", " .$resCliSec['numero']. " " .$resCliSec['complemento']. ", " .$resCliSec['bairro']. ", CEP: " .$resCliSec['cep']. ", " .$resCliSec['cidade']. " - " .strtoupper($resCliSec['estado']). "	";
    $content .= "e ";
    if($resCliSec['pessoa'] == 'F'){        if(!empty($resCliSec['nome']))            $content .= "<b>" . strtoupper($resCliSec['nome']). ", </b>";
        if(!empty($resCliSec['nacionalidade']))            $content .= "" . $resCliSec['nacionalidade']. ", " ;
        if(!empty($resCliSec['estado_civil']))            $content .= "" . RetornaEstadoCivil($resCliSec['estado_civil']). ", " ;
        if(!empty($resCliSec['profissao']))            $content .= "" . $resCliSec['profissao']. ", " ;
        if(!empty($resCliSec['rg']))            $content .= "portador da cédula de identidade, RG nº " .$resCliSec['rg']. ", ";
        if(!empty($resCliSec['cpf']))            $content .= "inscrito no CPF nº " .$resCliSec['cpf']. " ";
    }    if($resCliSec['pessoa'] == 'J'){        if(!empty($resCliSec['razao']))            $content .= " " .strtoupper($resCliSec['razao']). ", </b>";
        if(!empty($resCliSec['cnpj']))            $content .= "inscrita no CNPJ/MF sob o nº " .$resCliSec['cnpj']. ", ";
        if(!empty($resCliSec['inscricao']))            $content .= "inscrição estadual o nº " .$resCliSec['inscricao']. " ";
    }    if(!empty($resCliSec['logradouro']))        $content .= "residente e domiciliado na " .$resCliSec['logradouro']. ", ";
    if(!empty($resCliSec['numero']))        $content .= "" . $resCliSec['numero']. ", ";
    if(!empty($resCliSec['complemento']))        $content .= "" . $resCliSec['complemento']. ", ";
    if(!empty($resCliSec['bairro']))        $content .= "" . $resCliSec['bairro']. ", ";
    if(!empty($resCliSec['cep']))        $content .= "CEP: " .$resCliSec['cep']. " ";
    if(!empty($resCliSec['cidade']))        $content .= "" . $resCliSec['cidade']. " - " .strtoupper($resCliSec['estado']). " ";
    if(!empty($resCliSec['responsavel'])){        $content .= "Responsavel: " . $resCliSec['responsavel']. ", ";
        if(!empty($resCliSec['logradouroContato']))            $content .= "responsavel residente e domiciliado na " .$resCliSec['logradouroContato']. ", ";
        if(!empty($resCliSec['numeroContato']))            $content .= "" . $resCliSec['numeroContato']. ", ";
        if(!empty($resCliSec['complementoContato']))            $content .= "" . $resCliSec['complementoContato']. ", ";
        if(!empty($resCliSec['bairroContato']))            $content .= "" . $resCliSec['bairroContato']. ", ";
        if(!empty($resCliSec['cepContato']))            $content .= "CEP: " .$resCliSec['cepContato']. " ";
        if(!empty($resCliSec['cidadeContato']))            $content .= "" . $resCliSec['cidadeContato']. " - " .strtoupper($resCliSec['estadoContato']). " ";
        if(!empty($resCliSec['email_responsavel']))            $content .= "" . $resCliSec['email_responsavel']. ", ";
    }}$content .= "</strong>";
